/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#526442',
        'primary-dim': '#475737',
        'primary-container': '#d5e9bf',
        'on-primary': '#eaffd3',
        'on-primary-container': '#465736',
        'secondary': '#52616a',
        'secondary-dim': '#46555e',
        'secondary-container': '#d5e5ef',
        'on-secondary': '#f3faff',
        'on-secondary-container': '#45545c',
        'tertiary': '#745c00',
        'tertiary-container': '#f5ce53',
        'on-tertiary-container': '#584500',
        'error': '#9f403d',
        'error-container': '#fe8983',
        'on-error': '#fff7f6',
        'background': '#f8f9fa',
        'on-background': '#2b3437',
        'surface': '#f8f9fa',
        'surface-dim': '#d1dce0',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f6',
        'surface-container': '#eaeff1',
        'surface-container-high': '#e3e9ec',
        'surface-container-highest': '#dbe4e7',
        'on-surface': '#2b3437',
        'on-surface-variant': '#586064',
        'outline': '#737c7f',
        'outline-variant': '#abb3b7',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        '3xl': '1rem',
      },
    },
  },
  plugins: [],
}
